version: "3.3"
services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "50050"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./server/data:/data/db
    ports:
      - "27017"
  envoy:
    container_name: envoy
    restart: always
    build: ./envoy
    ports: 
      - "8080"
    